# Reek configuration
# The lexer is inherently complex and table-driven; exclude it from high-churn detectors.
# Core parser/evaluator/unifier paths are algorithmic and currently exceed Reek thresholds;
# suppress targeted detectors to keep the signal actionable until a deeper refactor.
# TODO(2026-02-09): Narrow these exclusions as evaluator/parser refactors progress.

detectors:
  TooManyMethods:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Parser
      - Ruby::Rego::Compiler
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Evaluator::RuleEvaluator
      - Ruby::Rego::Unifier
  TooManyConstants:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::OperatorEvaluator
  TooManyInstanceVariables:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::ReferenceResolver
  TooManyStatements:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Parser
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Evaluator::RuleEvaluator
      - Ruby::Rego::Evaluator::OperatorEvaluator
      - Ruby::Rego::Unifier
      - Ruby::Rego::WithModifiers::WithModifierBuiltinOverride
      - Ruby::Rego::ParserError#initialize
      - Ruby::Rego::TypeError#initialize
      - Ruby::Rego::UnificationError#initialize
  DuplicateMethodCall:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Evaluator::RuleEvaluator
      - Ruby::Rego::Unifier
      - Ruby::Rego::WithModifiers::WithModifierBuiltinOverride
  UtilityFunction:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Unifier
  FeatureEnvy:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::RuleEvaluator
      - Ruby::Rego::Evaluator::ReferenceKeyResolver
      - Ruby::Rego::Evaluator::BoundVariableCollector
      - Ruby::Rego::Unifier
  ControlParameter:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::RuleEvaluator
      - Ruby::Rego::Unifier
      - Ruby::Rego::WithModifiers::WithModifierBuiltinOverride
  NilCheck:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Unifier
  RepeatedConditional:
    exclude:
      - Ruby::Rego::Lexer
      - Ruby::Rego::Evaluator::ReferenceResolver
      - Ruby::Rego::Evaluator::RuleEvaluator
  NestedIterators:
    exclude:
      - Ruby::Rego::Evaluator::RuleEvaluator
  UncommunicativeVariableName:
    accept:
      - e
      - _
    exclude:
      - Ruby::Rego::Builtins::Collections::ObjectOps#self.object_remove
      - Ruby::Rego::Evaluator::ExpressionDispatch#handler_for
