name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --format simple --no-color
      - name: Run Reek
        run: bundle exec reek lib

  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Steep
        run: bundle exec steep check
      - name: Run bundler-audit
        run: bundle exec bundler-audit check
